"Down" hosts not parsed
Ayrx/nmap_xml_parser pull request #6
Opened 2020-06-18 13:51 UTC by sciguy16

When running nmap with `-v` it stores "down" hosts in the XML output, but these do not have `starttime`, `endtime` or `ports` fields. I've set the start and end times to default to `0` if these are missing, and set the ports field to default to an empty list of ports.

I've also added this XML file as an integration test:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE nmaprun>
<?xml-stylesheet href="file:///usr/bin/../share/nmap/nmap.xsl" type="text/xsl"?>

<nmaprun scanner="nmap" args="nmap -p 1234 -oX host-down.xml -v 192.168.59.234/30" start="1592485655" startstr="Thu Jun 18 14:07:35 2020" version="7.80" xmloutputversion="1.04">
<scaninfo type="syn" protocol="tcp" numservices="1" services="1234"/>
<verbose level="1"/>
<debugging level="0"/>
<taskbegin task="ARP Ping Scan" time="1592485655"/>
<taskend task="ARP Ping Scan" time="1592485655" extrainfo="4 total hosts"/>
<host><status state="down" reason="no-response" reason_ttl="0"/>
<address addr="192.168.59.232" addrtype="ipv4"/>
</host>
<host><status state="down" reason="no-response" reason_ttl="0"/>
<address addr="192.168.59.233" addrtype="ipv4"/>
</host>
<host><status state="down" reason="no-response" reason_ttl="0"/>
<address addr="192.168.59.234" addrtype="ipv4"/>
</host>
<host><status state="down" reason="no-response" reason_ttl="0"/>
<address addr="192.168.59.235" addrtype="ipv4"/>
</host>
<runstats><finished time="1592485655" timestr="Thu Jun 18 14:07:35 2020" elapsed="0.58" summary="Nmap done at Thu Jun 18 14:07:35 2020; 4 IP addresses (0 hosts up) scanned in 0.58 seconds" exit="success"/><hosts up="0" down="4" total="4"/>
</runstats>
</nmaprun>
```

2020-06-18 14:05 UTC, Ayrx commented
Thanks for the contribution! I'll review this sometime this weekend. :)

2020-07-03 03:00 UTC, Ayrx requested changes
Hi, sorry I took so long on this PR.

The changes mostly LGTM but you could you change `scan_start_time` and `scan_end_time` to `Option<i64>` and use that to signal that the field is missing instead of setting the values to `0` and add a few tests to assert that?

I'll merge this PR once those changes are made. :)

2020-07-07 11:11 UTC, sciguy16 commented
Not a problem, I've updated the start and end times to `Option<i64>` and added some unit tests.

2020-07-12 13:06 UTC, Ayrx approved these changes

2020-07-12 13:07 UTC, merged

2020-07-12 13:07 UTC, Ayrx commented
Thanks for the pull request!